import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import type { ProjectTemplateAdapter } from '../index';
import type { TemplateSpec } from '../spec';

const spec: TemplateSpec = {
  type: 'next-app',
  displayName: 'Next.js App',
  description: 'Next.js 15 + Tailwind 4 + TypeScript + Vercel workspace',
  pipeline: {
    columns: [
      { id: 'backlog', label: 'Backlog' },
      { id: 'in-progress', label: 'In Progress' },
      { id: 'in-review', label: 'In Review' },
      { id: 'shipped', label: 'Shipped' },
    ],
    transitions: [
      { from: 'backlog', to: 'in-progress', gates: ['criteria.md written', 'next build passes'] },
      { from: 'in-progress', to: 'in-review', gates: ['all criteria have implementation', 'next build passes'] },
      { from: 'in-review', to: 'shipped', gates: ['all criteria verified', 'next build passes', 'deployed to vercel'] },
      { from: 'in-review', to: 'in-progress', gates: ['verification failed'] },
    ],
  },
  cardTypes: [
    { id: 'feature', label: 'Feature', fields: [] },
    { id: 'bug', label: 'Bug', fields: [] },
    { id: 'page', label: 'Page', fields: [] },
  ],
  fields: [
    { id: 'title', label: 'Title', type: 'text', required: true },
    { id: 'description', label: 'Description', type: 'textarea' },
    { id: 'vercelUrl', label: 'Vercel URL', type: 'text' },
  ],
};

export const nextAppAdapter: ProjectTemplateAdapter = {
  type: 'next-app',
  displayName: 'Next.js App',
  description: 'Next.js 15 + Tailwind 4 + TypeScript + Vercel workspace',
  spec,
  scaffold(name: string, dest: string): void {
    const dir = (path: string) => mkdirSync(join(dest, path), { recursive: true });
    const file = (path: string, content: string) => writeFileSync(join(dest, path), content, 'utf8');

    dir('src/app');
    dir('src/components');
    dir('public');

    file(
      'package.json',
      JSON.stringify(
        {
          name,
          version: '0.1.0',
          private: true,
          scripts: {
            dev: 'next dev --turbopack',
            build: 'next build',
            start: 'next start',
            lint: 'next lint',
          },
          dependencies: {
            next: '^15.0.0',
            react: '^19.0.0',
            'react-dom': '^19.0.0',
          },
          devDependencies: {
            '@tailwindcss/postcss': '^4',
            '@types/node': '^20',
            '@types/react': '^19',
            '@types/react-dom': '^19',
            tailwindcss: '^4',
            typescript: '^5',
          },
        },
        null,
        2,
      ) + '\n',
    );

    file(
      'tsconfig.json',
      JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2022',
            lib: ['dom', 'dom.iterable', 'esnext'],
            allowJs: false,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: 'esnext',
            moduleResolution: 'bundler',
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: 'preserve',
            incremental: true,
            plugins: [{ name: 'next' }],
            paths: { '@/*': ['./src/*'] },
          },
          include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
          exclude: ['node_modules'],
        },
        null,
        2,
      ) + '\n',
    );

    file(
      'next.config.ts',
      `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
`,
    );

    file(
      'postcss.config.mjs',
      `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
export default config;
`,
    );

    file('src/app/globals.css', `@import "tailwindcss";\n`);

    file(
      'src/app/layout.tsx',
      `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${name}",
  description: "Generated by new-next",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    );

    file(
      'src/app/page.tsx',
      `export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-2xl font-bold">${name}</h1>
    </main>
  );
}
`,
    );

    file(
      'vercel.json',
      JSON.stringify(
        {
          framework: 'nextjs',
          buildCommand: 'bun run build',
          devCommand: 'bun run dev',
          installCommand: 'bun install',
        },
        null,
        2,
      ) + '\n',
    );

    file(
      '.gitignore',
      `.next/
out/
node_modules/
.env*.local
.vercel
*.tsbuildinfo
`,
    );

    if (process.env.AM_SKIP_TEMPLATE_INSTALL !== '1') {
      const install = spawnSync('bun', ['install'], { cwd: dest, stdio: 'inherit' });
      if (install.status !== 0) {
        process.stderr.write('warning: bun install failed — run it manually\n');
      }
    }
  },
};
