#!/usr/bin/env bun
/**
 * new-next — Scaffold a Next.js workspace (TypeScript, Tailwind 4, Bun, Turbopack, Vercel).
 *
 * Usage:
 *   new-next <name>
 *
 * Creates workspaces/<name>/ with a minimal Next.js 15+ app configured for:
 *   - TypeScript strict mode
 *   - Tailwind CSS v4 (PostCSS plugin)
 *   - Bun as package manager
 *   - Turbopack dev server
 *   - Vercel deployment (vercel.json)
 */

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";

// ---------------------------------------------------------------------------
// Arg validation
// ---------------------------------------------------------------------------

const name = process.argv[2];
if (!name || name.startsWith("-")) {
  process.stderr.write("Usage: new-next <name>\n");
  process.exit(1);
}
if (!/^[a-z0-9-]+$/.test(name)) {
  process.stderr.write("error: name must be lowercase alphanumeric with hyphens only\n");
  process.exit(1);
}

const repoRoot = resolve(import.meta.dir, "..");
const dest = join(repoRoot, "workspaces", name);

if (existsSync(dest)) {
  process.stderr.write(`error: workspaces/${name} already exists\n`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Scaffold
// ---------------------------------------------------------------------------

function dir(path: string): void {
  mkdirSync(join(dest, path), { recursive: true });
}

function file(path: string, content: string): void {
  writeFileSync(join(dest, path), content, "utf8");
}

console.log(`Scaffolding workspaces/${name}...`);

dir("src/app");
dir("src/components");
dir("public");

// package.json
file(
  "package.json",
  JSON.stringify(
    {
      name,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev --turbopack",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "^15.0.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
      },
      devDependencies: {
        "@tailwindcss/postcss": "^4",
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        tailwindcss: "^4",
        typescript: "^5",
      },
    },
    null,
    2,
  ) + "\n",
);

// tsconfig.json
file(
  "tsconfig.json",
  JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: false,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2,
  ) + "\n",
);

// next.config.ts
file(
  "next.config.ts",
  `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
`,
);

// postcss.config.mjs (Tailwind v4)
file(
  "postcss.config.mjs",
  `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
export default config;
`,
);

// src/app/globals.css
file(
  "src/app/globals.css",
  `@import "tailwindcss";
`,
);

// src/app/layout.tsx
file(
  "src/app/layout.tsx",
  `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${name}",
  description: "Generated by new-next",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
);

// src/app/page.tsx
file(
  "src/app/page.tsx",
  `export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-2xl font-bold">${name}</h1>
    </main>
  );
}
`,
);

// vercel.json
file(
  "vercel.json",
  JSON.stringify(
    {
      framework: "nextjs",
      buildCommand: "bun run build",
      devCommand: "bun run dev",
      installCommand: "bun install",
    },
    null,
    2,
  ) + "\n",
);

// .gitignore
file(
  ".gitignore",
  `.next/
out/
node_modules/
.env*.local
.vercel
*.tsbuildinfo
`,
);

// ---------------------------------------------------------------------------
// Install dependencies
// ---------------------------------------------------------------------------

console.log("Installing dependencies with bun...");
const install = spawnSync("bun", ["install"], {
  cwd: dest,
  stdio: "inherit",
});

if (install.status !== 0) {
  process.stderr.write("warning: bun install failed — run it manually\n");
}

console.log(`\nDone. Run:\n  cd workspaces/${name}\n  bun run dev\n`);
